[package]
name = "nihav-bench"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]

[dependencies]

[dev-dependencies]
criterion = "0.2"
rand = "0.5"

[[bench]]
name = "rv34_add_coeffs"
harness = false
